### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GoogleWasAllMyIdea** [Ariakim-Taiyo/Geofs-Fly-By-Wire#1]
This is ONLY A QUESTION. Is there a way to put this in a bookmarklet so that I can use it at school too. I have a pc so i can paste it and it works great but I wondered if it would be possible to have a bookmark for this?

**Comment by GoogleWasAllMyIdea** [comment]
Also I was wondering if there was a way to create a code you could just paste into console to make the plane's rpm really fast? (The speed hack) I think that is possible that way i do not have to open console and type in geofs.aircraft.instance.setup and then set the rpm, I just want to be able to open console and paste something in (hit enter) and be done with it just like your fly by wire code.

**Comment by Ariakim-Taiyo** [comment]
To make it into a bookmarklet, just add

javascript: (() => {
  // Your code here!
})();

then copy the code and place it in the commented portion and set it as a bookmark.

As for the code for "speed hacking", the method varies depending on what aircraft is being used. Every aircraft uses different part names for the engines, so it is more difficult to create a script that would work on all of them.

You can change the thrust itself by using 

geofs.aircraft.instance.parts."engine name".thrust = //your thrust value

**Comment by GoogleWasAllMyIdea** [comment]
Thank you so much!!!! I love this!

**Comment by GoogleWasAllMyIdea** [comment]
P er fection

**Comment by GoogleWasAllMyIdea** [comment]
For the Rpm can I edit the code to say what I want then save that and be able to paste it into console? I tried but I must be editing it wrong. I just want to edit the thrust on the 737-700 to make it more powerful or even less powerful. No other plane really. I just want to be able to have a line of code I can edit and then paste into console and it will work.

**Comment by GoogleWasAllMyIdea** [comment]
I also have no idea what the engine name for the 737-700 is or how to find engine names because I am stupid

**Comment by Ariakim-Taiyo** [comment]
for the 737-700, use the following code:
geofs.aircraft.instance.parts.engine1.thrust = //your thrust amount here
geofs.aircraft.instance.parts.engine2.thrust = //your thrust amount here

**Comment by GoogleWasAllMyIdea** [comment]
Thanks. Also your 777 engine sounds wrok on the 737 they are just very loud. But still work!
